export const emojiTheme = {
  logo: "svg:icons/logo",
  info: "ℹ️",
  ok: "✅",
  error: "⚠️",
  tablero: "📊",
  pacientes: "🙋🏻‍♀️",
  perfil: "🆔",
  cargas: "📤",
  agenda: "🗓️",
  calendario: "🗓️",
  laboratorio: "🧪",
  banco: "🏦",
  megafono: "📣",
  plan: "🗒️",
  pago: "💳",
  reportes: "📈",
  grafica: "📊",
  tabla: "📋",
  recordatorios: "⏰",
  recetas: "💊",
  plantilla: "🧾",
  actualizar: "🔁",
  nube: "☁️",
  atras: "⬅️",
  llave: "🔑",
  firma: "✍️",
  pdf: "📄",
  buscador: "🔎",
  trabajo: "💼",
  archivo: "📄",
  carpeta: "📁",
  documentos: "📚",
  subir: "📤",
  subirBandeja: "🗂️",
  descargar: "⬇️",
  enlace: "🔗",
  ver: "👁️‍🗨️",
  borrar: "🗑️",
  copiar: "📋",
  refrescar: "🔄",
  desbloquear: "🔓",
  usuario: "👤",
  imagen: "📸",
  limpiar: "🧹",
  salir: "🚪",
  buscar: "🔍",
  siguiente: "➡️",
  anterior: "⬅️",
  email: "✉️",
  candado: "🔒",
  guardar: "💾",
  hoja: "📄",
  alerta: "⚠️",
  home: "🏠",
  instalar: "⬇️",
  ios: "",
  android: "🤖",
  escritorio: "🖥️",
  busqueda: "🔎",
  dashboard: "📊",
  puzzle: "🧩",
  reloj: "⏳",
  exportar: "📄",
  eliminar: "❎",
  nuevo: "✨",
  compartir: "🫱🏻‍🫲🏼",
  ajustes: "⚙️",
  ajustes2: "🛠️",
  ayuda: "🆘",
  chat: "💬",
  notificaciones: "🔔",
  ArrowLeft: "⬅️",
  Loader2: "🔄",
  Trash2: "🗑️",
  Download: "📥",
  Copy: "📋",
  History: "🕒",
  web: "🌐",
  leaf: "🍃",
  google: "G",
};

export const EMOJI_FALLBACK_TOKEN = "info";
