name: Check Sentry secrets
on:
  workflow_dispatch: {} # te permite ejecutarlo manualmente

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check presence of secrets
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          for v in SENTRY_AUTH_TOKEN SENTRY_ORG SENTRY_PROJECT; do
            if [ -z "${!v}" ]; then
              echo "::error title=Missing secret::$v is empty or not set"
              exit 1
            else
              echo "$v is set ✅"
            fi
          done

      - name: Check Sentry connectivity
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        run: |
          npm i -g @sentry/cli
          # Muestra información de tu org si el token es válido
          sentry-cli --org "$SENTRY_ORG" info
