name: CI - Build & Sentry Sourcemaps

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Sentry (Settings > Secrets and variables > Actions)
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_RELEASE: ${{ github.sha }}
      NEXT_PUBLIC_SENTRY_ENV: production

      # App vars
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_SITE_URL: https://example.com

      # DSN (elige una de las dos líneas; comenta la otra)
      # NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      NEXT_PUBLIC_SENTRY_DSN: ${{ vars.NEXT_PUBLIC_SENTRY_DSN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # Node 20.x
          cache: 'pnpm'        # habilita caché para pnpm (requiere pnpm instalado)

      # **Clave**: activar Corepack y la versión de pnpm del packageManager
      - name: Enable Corepack
        run: corepack enable

      - name: Use repo's pnpm version
        run: corepack prepare pnpm@10.17.1 --activate

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload .next artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: ignore
