# .github/workflows/ci.yml
name: CI - Build & Sentry Sourcemaps

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_RELEASE: ${{ github.sha }}
      NEXT_PUBLIC_SENTRY_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_SITE_URL: https://example.com
      NEXT_PUBLIC_SENTRY_DSN: ${{ vars.NEXT_PUBLIC_SENTRY_DSN }}
      # Si prefieres secret en vez de vars:
      # NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Habilita Corepack y PNPM (lee la versión desde package.json: "packageManager")
      - name: Setup PNPM (from packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          # opcional: package_json_path: ./package.json

      # 2) Node DESPUÉS de pnpm para que funcione el cache: 'pnpm'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Show versions
        run: |
          node -v
          pnpm -v
          which pnpm
          corepack -v || true

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload .next artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: ignore
