# .github/workflows/ci.yml
name: CI - Build & Sentry Sourcemaps

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_RELEASE: ${{ github.sha }}
      NEXT_PUBLIC_SENTRY_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_SITE_URL: https://example.com
      # Si usas vars de org:
      NEXT_PUBLIC_SENTRY_DSN: ${{ vars.NEXT_PUBLIC_SENTRY_DSN }}
      # O si prefieres secret, comenta la de arriba y descomenta esta:
      # NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node primero (caché pnpm nativa)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'                # Alineado con tu entorno local
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # pnpm sin "version": usa package.json: "packageManager": "pnpm@10.17.1"
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Show versions
        run: |
          node -v
          pnpm -v
          which pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload .next artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: ignore
